---

- hosts: all

  tasks:
    - name: show run
      ios_config:
        backup: yes
        backup_options:
          dir_path: /home/awx
      
      register: backup_ios_location
      when: ansible_network_os == 'ios'

    - name: show path
      debug: msg={{ backup_ios_location }}
